
    <!-- BEGIN SIDEBAR -->
    <div class="sidebar col-md-3 col-sm-5">
        <ul class="list-group margin-bottom-25 sidebar-menu">
            <li class="list-group-item clearfix dropdown active">
                <a href="javascript:void(0);" class="collapsed">
                    <i class="fa fa-angle-right"></i>
                    Рубрики
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu" style="display:block;">
                    <li class="list-group-item  clearfix "><a href="javascript:void(0);" ><i class="fa fa-circle"></i> СВАДЬБЫ</a></li>

                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> ДЕТСКИЕ ПРАЗДНИКИ </i></a></li>
                    <li><a href="javascript:void(0);" class="collapsed"><i class="fa fa-circle"></i> ВЫПУСКНОЙ БАЛ </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> КАЛЕНДАРНЫЕ ПРАЗДНИКИ </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> ЮБИЛЕИ </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> РОЖДЕНИЕ МАЛЫША </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Выписка из роддома </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> ДЕТСКИЕ ПРАЗДНИКИ</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> ВЫПУСКНОЙ БАЛ</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> ЮБИЛЕИИ</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Новый год и Рождество</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> 23 февраля</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> 8 марта</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> 9 мая</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> КОРПОРАТИВНЫЕ МЕРОПРИЯТИЯ</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> ПРЕЗЕНТАЦИИ И ОТКРЫТИЯ</a></li>
                </ul>
            </li>
            <li class="list-group-item clearfix dropdown active">
                <a href="javascript:void(0);">
                    <i class="fa fa-angle-right"></i>
                    Услуги
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Проведение торжеств</i></a></li>
                    <li><a href="javascript:void(0);" class="collapsed"><i class="fa fa-circle"></i> Праздник «под ключ» </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Фото</i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Видео </i></a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Ведущие, ди-джеи </i></a></li>
                    <li>
                        <a href="javascript:void(0);" class="collapsed"><i class="fa fa-circle "></i> Артисты </i><i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu" style="display:block;">
                            <li >
                                <a href="javascript:void(0);"><i class="fa fa-circle"></i> ТАНЦОРЫ</a>
                            </li>
                            <li >
                                <a href="javascript:void(0);" ><i class="fa fa-circle"></i> ФОКУРСНИКИ </a>
                            </li>
                            <li >
                                <a href="javascript:void(0);" ><i class="fa fa-circle"></i> КЛОУНЫ </a>
                            </li>
                            <li >
                                <a href="javascript:void(0);" ><i class="fa fa-circle"></i> ЮМОРИСТЫ </a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Аниматоры</a></li>
                    <li>
                        <a href="javascript:void(0);" class="collapsed"><i class="fa fa-circle " ></i> Эксклюзивные услуги </i><i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu" style="display:block;">
                            <li >
                                <a href="javascript:void(0);"><i class="fa fa-circle"></i> мимы</a>
                            </li>
                            <li >
                                <a href="javascript:void(0);" ><i class="fa fa-circle"></i> шаржисты </a>
                            </li>
                            <li >
                                <a href="javascript:void(0);" ><i class="fa fa-circle"></i> живые статуи </a>
                            </li>
                            <li >
                                <a href="javascript:void(0);" ><i class="fa fa-circle"></i> костюмированное шоу </a>
                            </li>
                        </ul>
                    </li>

                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Цветы</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Прокат автомобилей</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Проведение мастер-классов</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Выездная регистрация</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Приглашения</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Аксессуары ручной работы</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Свадебные аксессуары</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Салюты, фейерверки</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Огненное/лазерное шоу</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Подарки</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Гостиницы</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Кафе, бары</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Рестораны</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Банкетные залы</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Столовые</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Оформление залов</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Салоны красоты</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Парикмахеры</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Стилисты</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Визажисты</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Маникюр</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Сюрпризы детям</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i>Дед Мороз и Снегурочка</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Романтические признания</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Меха</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Ювелирные салоны</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Мужская одежда</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Свадебные салоны</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Вечерние наряды</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Праздничная одежда для детей</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Детские товары от 0 до 14</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Услуги такси</a></li>
                    <li><a href="javascript:void(0);"><i class="fa fa-circle"></i> Оборудование в аренду</a></li>
                </ul>
            </li>
        </ul>

        <!--            <div class="sidebar-filter margin-bottom-25">-->
        <!--                <h2>Filter</h2>-->
        <!--                <h3>Availability</h3>-->
        <!--                <div class="checkbox-list">-->
        <!--                    <label><input type="checkbox"> Not Available (3)</label>-->
        <!--                    <label><input type="checkbox"> In Stock (26)</label>-->
        <!--                </div>-->
        <!---->
        <!--                <h3>Price</h3>-->
        <!--                <p>-->
        <!--                    <label for="amount">Range:</label>-->
        <!--                    <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;">-->
        <!--                </p>-->
        <!--                <div id="slider-range"></div>-->
        <!--            </div>-->

        <div class="clearfix"> </div>
    </div>
    <!-- END SIDEBAR -->