<div class="container">
    <div class="page-slider margin-bottom-35">
        <div id="layerslider" style="width: 100%; height: 300px; margin: 0 auto;">

            <div class="ls-layer ls-layer1" style="slidedirection: left; transition2d: 24,25,27,28; ">
                <img src="/img/full3.jpg" class="ls-bg" alt="Slide background">
                <div class="ls-s-1 title" style=" top: 50px; left: 35%; slidedirection : fade; slideoutdirection : fade; durationin : 750; durationout : 750; easingin : easeOutQuint; rotatein : 90; rotateout : -90; scalein : .5; scaleout : .5; showuntil : 4000; white-space: nowrap;">
                    Подарите <strong>своей любимой</strong> не забываемое
                </div>
                <div class="ls-s-1 mini-text" style=" top: 338px; left: 35%; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 300; showuntil : 4000; white-space: nowrap;">
                    Мы поможем вам выбрать именно то, что вы ищите - <br>
                    с нами жизнь становится сказкой
                </div>
            </div>
            <div class="ls-layer ls-layer1" style="slidedirection: right; transition2d: 92,93,105; ">
                <img src="/img/full5.jpg" class="ls-bg" alt="Slide background">
                <div class="ls-s-1 title" style=" top: 35%; left: 60%; slidedirection : fade; slideoutdirection : fade; durationin : 750; durationout : 750; easingin : easeOutQuint; rotatein : 90; rotateout : -90; scalein : .5; scaleout : .5; showuntil : 8000; white-space: nowrap;">
                    Эксклюзивные<br>
                    столики
                </div>

                <div class="ls-s-1 mini-text" style=" top: 70%; left: 60%; slidedirection : fade; slideoutdirection : fade; durationout : 750; easingin : easeOutQuint; delayin : 300; scalein : .8; scaleout : .8; showuntil : 8000; white-space: nowrap;">
                    <span>Огромный выбор в цене</span>
                    <button type="button" class="btn dark" style="padding: 7px 20px 8px; background-color: #000; margin-left: 10px;">Заказать</button>
                </div>
            </div>
            <div class="ls-layer ls-layer1" style="slidedirection: right; transition2d: 24,25,27,28; ">
                <img src="/img/full4.jpg" class="ls-bg" alt="Slide background">

            </div>
        </div>
    </div>
</div>