<div class="pre-header" style="padding: 0;">
    <div class="container">
        <ul class="nav navbar-nav center">
            <li class="wedding"><a href="javascript:void(0);">Свадьба</a></li>
            <li><a href="javascript:void(0);">Рождение малыша</a></li>
            <li><a href="javascript:void(0);">Презентации</a></li>
            <li><a href="javascript:void(0);">Выпускной бал</a></li>
            <li><a href="javascript:void(0);">Юбилей</a></li>
            <li><a href="javascript:void(0);">Новый год</a></li>
            <li><a href="javascript:void(0);">Детские праздники</a></li>
        </ul>
    </div>
</div>