<h2>Рекомендуемые статьи</h2>
<div class="bxslider-wrapper">
    <ul class="bxslider" data-slides-phone="1" data-slides-tablet="2" data-slides-desktop="3" data-slide-margin="15">
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/10_podarkov_dlya_nevesty_na_8_marta_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">УТРО НЕВЕСТЫ В НЕЖНЫХ ПАСТЕЛЬНЫХ ТОНАХ</a></h3>
            </div>
        </li>
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/detskii_stol_na_svadbe_main_2_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">ПОКУПКА СВАДЕБНОГО ПЛАТЬЯ ЧЕРЕЗ ИНТЕРНЕТ: ПЛЮСЫ И МИНУСЫ</a></h3>
            </div>
        </li>
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/pokupka_svadebnogo_platya_cherez_internet_main_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">СВАДЬБА В СТИЛЕ ГОЛЛИВУД: КИРИЛЛ И АННА</a></h3>
            </div>
        </li>
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/svadebnie_platya_zoog_bridal_2015_main_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">ЛЕДЯНАЯ ГЕОМЕТРИЯ: СВАДЕБНАЯ ФОТОСЕССИЯ В СТУДИИ</a></h3>
            </div>
        </li>
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/utro_nevesty_v_nejnih_pastelnih_tonah_main_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">10 ПОДАРКОВ ДЛЯ НЕВЕСТЫ НА 8 МАРТА</a></h3>
            </div>
        </li>
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/zimnyaya_svadebnaya_fotosessiya_v_geometricheskom_stile_main_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">ДЕТСКИЙ СТОЛ НА СВАДЬБЕ: МЕНЮ И ОФОРМЛЕНИЕ</a></h3>
            </div>
        </li>
        <li>
            <div class="product-item">
                <div class="pi-img-wrapper">
                    <a href="javascript:void(0);"><img src="/img/recommended-articles/zabavnie_foto_jeniha_s_druzyami_main_306.jpg" class="img-responsive" alt=""></a>
                </div>
                <h3><a href="item.html">20 ЗАБАВНЫХ ФОТО ДРУЗЕЙ ЖЕНИХА</a></h3>
            </div>
        </li>
    </ul>
</div>